### PR TITLE
Create xephov

### PR DESCRIPTION
**Pull request by LMGXENON**

### CODE REVIEW

**Comment by rayhanadev** [comment]
omg this is so beautiful 🥺

**Comment by LMGXENON** [comment]
Thank you!

**Comment by LMGXENON** [comment]
the subdomain is working but it isnt secure

**Comment by LMGXENON** [comment]
nvm I forgot to verify DNS configuration

**Comment by rayhanadev** [comment]
It's all good, do you need us to handle anything else? :)

**Pull request merged**
